#Desafio 04 - Crie um programa para ler algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informacoes possiveis
print()
print('##########')
print('DESAFIO 04')
print('##########\n')
print('- Crie um programa para ler algo pelo teclado e mostre na tela\no seu tipo primitivo e todas as informacoes possiveis.\n')
print()
print()
x = input('Digite algo para testarmos: ')
y = bool(x)
print()
print('O tipo primitivo desse valor é:', type(x))
print()
print('Testaremos o valor digitado, se True para verdadeiro ou False se falso.\n')
print('- Possui alguma informação digitada?', y)
print()
print('- Todo conteúdo é do tipo numérico? ', x.isnumeric())
print()
print('- Todo conteúdo é do tipo Letra?', x.isalpha())
print()
print('- Todo conteúdo é do tipo Alfanumério?', x.isalnum())
print()
print('- Todo conteúdo é do tipo Maiúscula?', x.isupper())
print()
print('- Todo conteúdo é do tipo Minúscula?', x.islower())
print()
print('- Só tem espaços?', x.isspace())
print()
print('- O conteudo pode ser usado como variável, função ou classe no Python?', x.isidentifier())#Verifica se a string pode ser usada como nome de uma variável, função ou classe no Python
print()
print('- Todo o conteúdo pertence a tabela ascii ?', x.isascii())#Verifica se todos os caracteres da string pertencem à tabela ASCII.
print()
print('- Todo o conteúdo pertence a case 10 (decimal), ou seja todo a strings contem numerios de 0 a 9?', x.isdecimal())#Retorna True apenas se a string contiver números de 0 a 9 (caracteres usados para formar números na base 10).
print()
print('- Todo o conteúdo possui numerios decimais ou caracteres numéricos especiais (numeros sobrescritos(expoentes) ou subscritos)?', x.isdigit())#Retorna True se a string contiver números decimais OU caracteres numéricos especiais, como números sobrescritos (expoentes) e subscritos.
print()
print('- O conteudo possui formato de título? Ou seja, cada palavra deve conter a primeira letra maiuscula.', x.istitle())#Capitalizada - O formato de título significa que a primeira letra de cada palavra deve estar em maiúscula e todas as demais letras devem estar em minúsculas.
print()
